add more checks

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -43,13 +43,14 @@ jobs:
       - name: Setup array args
         shell: bash
         run: |
-          ARGS=(--locked --target=x86_64-unknown-linux-gnu --verbose)
+          ARR=(--locked --target=x86_64-unknown-linux-gnu --verbose)
+          ARGS="${ARR[@]}"
 
       - name: Test array
         uses: ./
         with:
           command: build
-          args: $ARGS
+          args: eval ${ARGS}
           directory: test/hello_world
 
       - name: Make sure the following build folders exist
@@ -93,6 +94,12 @@ jobs:
           args: --release
           directory: test/hello_world
 
+      - name: Make sure the following build folders exist
+        shell: bash
+        run: |
+          [[ -d "test/hello_world/target/debug" ]] || (echo "debug is missing" && exit 1);
+          [[ -d "test/hello_world/target/release" ]] || (echo "release is missing" && exit 1);
+
   test-cross:
     name: "Test using cross"
     runs-on: ubuntu-latest
@@ -130,3 +137,9 @@ jobs:
           use-cross: true
           cross-version: 0.2.4
           directory: test/hello_world
+
+      - name: Make sure the following build folders exist
+        shell: bash
+        run: |
+          [[ -d "test/hello_world/target/aarch64-unknown-linux-gnu/debug" ]] || (echo "debug is missing" && exit 1);
+          [[ -d "test/hello_world/target/aarch64-unknown-linux-gnu/release" ]] || (echo "release is missing" && exit 1);
