add test for array input

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -40,6 +40,25 @@ jobs:
           args: --release
           directory: test/hello_world
 
+      - name: Setup array args
+        shell: bash
+        run: |
+          ARGS=(--locked --target=x86_64-unknown-linux-gnu --verbose)
+
+      - name: Test array
+        uses: ./
+        with:
+          command: build
+          args: $ARGS
+          directory: test/hello_world
+
+      - name: Make sure the following build folders exist
+        shell: bash
+        run: |
+          [[ -d "test/hello_world/target/debug" ]] || (echo "debug is missing" && exit 1);
+          [[ -d "test/hello_world/target/release" ]] || (echo "release is missing" && exit 1);
+          [[ -d "test/hello_world/target/x86_64-unknown-linux-gnu/debug" ]] || (echo "x86_64-unknown-linux-gnu/debug is missing" && exit 1);
+
   test-nightly:
     name: "Test nightly toolchain"
     runs-on: ubuntu-latest
@@ -54,7 +73,7 @@ jobs:
           toolchain: nightly
 
       - name: Enable Rust cache
-        uses: Swatinem/rust-cache@22c9328bcba27aa81a32b1bef27c7e3c78052531 # 2.0.1
+        uses: Swatinem/rust-cache@6fd3edff6979b79f87531400ad694fb7f2c84b1f # 2.2.1
         with:
           cache-on-failure: true
           workspaces: "./test/hello_world -> target"
@@ -89,7 +108,7 @@ jobs:
           target: aarch64-unknown-linux-gnu
 
       - name: Enable Rust cache
-        uses: Swatinem/rust-cache@22c9328bcba27aa81a32b1bef27c7e3c78052531 # 2.0.1
+        uses: Swatinem/rust-cache@6fd3edff6979b79f87531400ad694fb7f2c84b1f # 2.2.1
         with:
           cache-on-failure: true
           workspaces: "./test/hello_world -> target"
